#--------------------------------------------------------------------------------------#
#██████╗░░█████╗░███╗░░██╗██████╗░░█████╗░███╗░░░███╗███████╗███╗░░██╗██╗░░░██╗░██████╗#
#██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗████╗░████║██╔════╝████╗░██║██║░░░██║██╔════╝#
#██████╔╝███████║██╔██╗██║██║░░██║███████║██╔████╔██║█████╗░░██╔██╗██║██║░░░██║╚█████╗░#
#██╔═══╝░██╔══██║██║╚████║██║░░██║██╔══██║██║╚██╔╝██║██╔══╝░░██║╚████║██║░░░██║░╚═══██╗#
#██║░░░░░██║░░██║██║░╚███║██████╔╝██║░░██║██║░╚═╝░██║███████╗██║░╚███║╚██████╔╝██████╔╝#
#╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝╚═╝░░╚══╝░╚═════╝░╚═════╝░#
#--------------------------------------------------------------------------------------#
# ==================================================
#  SCRIPT INFO
# ==================================================
# Author: MrErrors
#
# Description:
#   Handles menu creation and interaction
#   for the PandaMenus plugin.
#
# ==================================================
verison: 1.0.0


# Debug Mode
# --------------------------------------------------
# When enabled:
# - Any errors during menu creation or interaction
#   will be sent to:
#     • All players with the permission:
#         pandamenus.debug
#     • The server console
#
# When disabled:
# - Errors will fail silently (no messages sent)
#
# Recommended:
# - Enable during development
# - Disable on production servers
# --------------------------------------------------
debug: true