#--------------------------------------------------------------------------------------#
#██████╗░░█████╗░███╗░░██╗██████╗░░█████╗░███╗░░░███╗███████╗███╗░░██╗██╗░░░██╗░██████╗#
#██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗████╗░████║██╔════╝████╗░██║██║░░░██║██╔════╝#
#██████╔╝███████║██╔██╗██║██║░░██║███████║██╔████╔██║█████╗░░██╔██╗██║██║░░░██║╚█████╗░#
#██╔═══╝░██╔══██║██║╚████║██║░░██║██╔══██║██║╚██╔╝██║██╔══╝░░██║╚████║██║░░░██║░╚═══██╗#
#██║░░░░░██║░░██║██║░╚███║██████╔╝██║░░██║██║░╚═╝░██║███████╗██║░╚███║╚██████╔╝██████╔╝#
#╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝╚═╝░░░░░╚═╝╚══════╝╚═╝░░╚══╝░╚═════╝░╚═════╝░#
#--------------------------------------------------------------------------------------#
#|================================================|#
#|					INFORMATION					  |#
#|================================================|#
# Script Author: 
# - MrErrors
#
verison: 1.0.0
debug: false


